group 'com.gsshop.mobile.flutter.flutter_hawk'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        jcenter()
        mavenCentral()
		maven { url 'https://jitpack.io' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace = 'com.gsshop.mobile.flutter.flutter_hawk'
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 16
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    // Hawk transitive Conceal(4KB .so) 제외 → 플러그인이 아래 AAR로만 Conceal 고정 (호스트 앱 Gradle에 의존하지 않음)
    implementation('com.orhanobut:hawk:2.0.1') {
        exclude group: 'com.facebook.conceal', module: 'conceal'
    }
    implementation files("${projectDir}/libs/conceal-1.1.3-16kb.aar")
}
